# Generated by Django 5.1.4 on 2025-01-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ttle', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Genre', models.CharField(choices=[('Fiction', 'fiction'), ('Nonfiction', 'Nonfiction'), ('History', 'History'), ('Psychology', 'Psychology')], max_length=100)),
                ('Description', models.TextField()),
                ('comments', models.TextField()),
                ('Rating', models.CharField(max_length=100)),
            ],
        ),
    ]
