# Generated by Django 5.1.4 on 2025-01-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comments',
            new_name='Comments',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Ttle',
            new_name='Title',
        ),
    ]
