# Generated by Django 5.1.4 on 2025-01-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_authentic_review_user_alter_review_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentic',
            name='name',
        ),
        migrations.AddField(
            model_name='authentic',
            name='first_name',
            field=models.CharField(default='Alice', max_length=100, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='authentic',
            name='last_name',
            field=models.CharField(default='carter', max_length=100, verbose_name='Last Name'),
        ),
    ]
